//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module2Topic1
{


    public partial class Site
    {
        protected global::System.Web.UI.WebControls.ContentPlaceHolder head;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1;
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
