//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module1Exercise1
{


    public partial class Exercise2
    {
        protected global::System.Web.UI.WebControls.Label firstName;
        protected global::System.Web.UI.WebControls.TextBox txtstate;
        protected global::System.Web.UI.WebControls.Label Label1;
        protected global::System.Web.UI.WebControls.TextBox txtstate1;
        protected global::System.Web.UI.WebControls.Label ageLabel;
        protected global::System.Web.UI.WebControls.TextBox whatAge;
        protected global::System.Web.UI.WebControls.Label dropDown;
        protected global::System.Web.UI.WebControls.DropDownList dropDownList;
        protected global::System.Web.UI.WebControls.Label radioButton;
        protected global::System.Web.UI.WebControls.RadioButtonList radioButtonList;
        protected global::System.Web.UI.WebControls.Label checkBox;
        protected global::System.Web.UI.WebControls.CheckBoxList checkBoxList;
        protected global::System.Web.UI.WebControls.FileUpload FileUpload1;

    }
}
